substitutions:
  name: "ceiling-fan"
  wifi_ap_password: ""

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: churchofcode.sonoff-mini-ceiling-fan
    version: "1.0.0"

esp8266:
  board: esp01_1m
  restore_from_flash: true

wifi:
  ap:
    password: ${wifi_ap_password}

logger:
api:
ota:
improv_serial:
captive_portal:

dashboard_import:
  package_import_url: github://churchofcode/esphome-importable/sonoff-mini/ceiling-fan.yaml@main
  import_full_config: true

######################################### Entities #########################################

binary_sensor:
  - name: ${name} Physical Button
    platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay_toggle
    entity_category: diagnostic
    disabled_by_default: true

  - name: ${name} Wired Switch Contacts
    platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay_toggle
    entity_category: diagnostic
    disabled_by_default: true

# This switch only exists because output.toggle doesn't exist
switch:
  - id: relay_toggle
    platform: output
    output: fan_output

output:
  - id: fan_output
    platform: gpio
    pin: GPIO12

fan:
  - name: ${name} Ceiling Fan
    id: ceiling_fan
    platform: binary
    output: fan_output
    restore_mode: ALWAYS_ON

##### Diagnostic #####

status_led:
  pin:
    number: GPIO13
    inverted: yes

button:
  - platform: safe_mode
    name: ${name} Safe Mode Boot
    entity_category: diagnostic
